### ISSUE TITLE
Device Plugin API was moved

### ISSUE THREAD

**Issue by sabyadi** [kubevirt/device-plugin-manager#10]
The Device Plugin API was moved from k8s.io/kubernetes/pkg/kubelet/apis/deviceplugin/v1beta1 to k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1, which causes problems. It would be great to have a new release with the correction.

**Comment by phoracek** [comment]
Thanks @sabyadi for reporting this. Would you be so kind and opened a PR moving the dependency? In case nothing but the place was changed, it should not be too much work I'm hoping.

**Comment by sabyadi** [comment]
Sure @phoracek, would it also be ok to migrate to go modules?

**Comment by phoracek** [comment]
That would be most welcome :) The library haven't received in quite some time...
