### ISSUE TITLE
Latest tag mis-labelled?

### ISSUE THREAD

**Issue by y2kenny** [kubevirt/device-plugin-manager#13]
Should the latest tag be 1.19.2 instead of 0.19.2?

**Comment by phoracek** [comment]
We tag with 0.x.y for each Kubernetes 1.x.y. This is following the format that other Kuberentes related libraries, e.g. client-go, follow https://github.com/kubernetes/client-go#versioning.

**Comment by y2kenny** [comment]
Ah ok.  Thanks for the clarification.
